version: '{build}'
pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\build.ps1
test: off
artifacts:
- path: '.\artifacts\**\*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: clUnJlfR9/a4dTu2340OT2XEgmQvFdDRwkqZbt2r+yTq4XAC+L536GpWhkSy4bu1
  on:
    branch: master
    appveyor_repo_tag: true